#!/usr/bin/env bash
# Validate or update TEI image digests in versions.lock.env (§3.10.9).
#
# Usage:
#   ./scripts/lock_tei_images.sh          # validate existing lock file
#   ./scripts/lock_tei_images.sh --update # pull source tags and rewrite lock file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSIONS_ENV="${REPO_ROOT}/versions.env"
LOCK_FILE="${REPO_ROOT}/versions.lock.env"

UPDATE=false
if [[ "${1:-}" == "--update" ]]; then
  UPDATE=true
elif [[ -n "${1:-}" ]]; then
  echo "lock_tei_images.sh: unknown argument: $1" >&2
  echo "Usage: ./scripts/lock_tei_images.sh [--update]" >&2
  exit 1
fi

if [[ ! -f "${VERSIONS_ENV}" ]]; then
  echo "lock_tei_images.sh: ${VERSIONS_ENV} not found" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${VERSIONS_ENV}"

for var in TEI_CPU_IMAGE_SOURCE TEI_GPU_IMAGE_SOURCE TEI_EXPECTED_VERSION; do
  if [[ -z "${!var:-}" ]]; then
    echo "lock_tei_images.sh: missing ${var} in versions.env" >&2
    exit 1
  fi
done

parse_semver() {
  local raw="$1"
  local version
  version="$(echo "${raw}" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true)"
  if [[ -z "${version}" ]]; then
    echo "lock_tei_images.sh: cannot parse semantic version from: ${raw}" >&2
    return 1
  fi
  printf '%s' "${version}"
}

is_gpu_tei_image() {
  local image_ref="$1"
  local label="$2"
  if [[ "${label}" == *GPU* ]] || [[ "${image_ref}" == *86-1.9* ]]; then
    return 0
  fi
  return 1
}

verify_tei_version() {
  local image_ref="$1"
  local label="$2"
  local stderr_file
  stderr_file="$(mktemp)"
  local -a run_args=(docker run --rm)
  if is_gpu_tei_image "${image_ref}" "${label}"; then
    run_args+=(--gpus all)
  fi
  run_args+=(--entrypoint text-embeddings-router "${image_ref}" --version)

  local output=""
  local run_exit=0
  output="$("${run_args[@]}" 2>"${stderr_file}" || run_exit=$?)"

  if [[ "${run_exit}" -ne 0 ]] || [[ -z "${output//[[:space:]]/}" ]]; then
    echo "lock_tei_images.sh: ${label} version command failed (exit=${run_exit})" >&2
    if [[ -s "${stderr_file}" ]]; then
      echo "lock_tei_images.sh: ${label} stderr:" >&2
      sed 's/^/  /' "${stderr_file}" >&2
    elif [[ "${run_exit}" -eq 0 ]]; then
      echo "lock_tei_images.sh: ${label} produced empty version output" >&2
    fi
    rm -f "${stderr_file}"
    return 1
  fi
  rm -f "${stderr_file}"

  local parsed
  parsed="$(parse_semver "${output}")"
  if [[ "${parsed}" != "${TEI_EXPECTED_VERSION}" ]]; then
    echo "lock_tei_images.sh: ${label} version ${parsed:-<unknown>} != TEI_EXPECTED_VERSION=${TEI_EXPECTED_VERSION}" >&2
    echo "lock_tei_images.sh: ${label} raw output: ${output}" >&2
    return 1
  fi
  echo "lock_tei_images.sh: ${label} version OK (${parsed})"
}

resolve_repo_digest() {
  local image_ref="$1"
  docker pull "${image_ref}" >/dev/null
  local repo_digest
  repo_digest="$(docker inspect --format='{{index .RepoDigests 0}}' "${image_ref}" 2>/dev/null || true)"
  if [[ -z "${repo_digest}" || "${repo_digest}" != *@sha256:* ]]; then
    echo "lock_tei_images.sh: failed to resolve RepoDigest for ${image_ref}" >&2
    return 1
  fi
  printf '%s' "${repo_digest}"
}

write_lock_file() {
  local cpu_image="$1"
  local gpu_image="$2"
  local tmp
  tmp="$(mktemp "${REPO_ROOT}/versions.lock.env.XXXXXX")"
  cat >"${tmp}" <<EOF
# TEI digest-locked images — generated by scripts/lock_tei_images.sh --update
TEI_CPU_IMAGE=${cpu_image}
TEI_GPU_IMAGE=${gpu_image}
EOF
  mv "${tmp}" "${LOCK_FILE}"
  echo "lock_tei_images.sh: updated ${LOCK_FILE}"
}

validate_lock_entry() {
  local var_name="$1"
  local value="${!var_name:-}"
  if [[ -z "${value}" || "${value}" != *@sha256:* ]]; then
    echo "lock_tei_images.sh: ${var_name} missing or invalid @sha256 digest" >&2
    return 1
  fi
  if [[ ! "${value}" =~ @sha256:[a-f0-9]{64}$ ]]; then
    echo "lock_tei_images.sh: ${var_name} digest format invalid" >&2
    return 1
  fi
  if [[ "${value}" =~ @sha256:0{64}$ ]]; then
    echo "lock_tei_images.sh: ${var_name} has placeholder digest" >&2
    return 1
  fi
  docker pull "${value}" >/dev/null
  verify_tei_version "${value}" "${var_name}"
}

if [[ "${UPDATE}" == true ]]; then
  echo "lock_tei_images.sh: pulling ${TEI_CPU_IMAGE_SOURCE}"
  verify_tei_version "${TEI_CPU_IMAGE_SOURCE}" "TEI_CPU_IMAGE_SOURCE"
  cpu_locked="$(resolve_repo_digest "${TEI_CPU_IMAGE_SOURCE}")"

  echo "lock_tei_images.sh: pulling ${TEI_GPU_IMAGE_SOURCE}"
  verify_tei_version "${TEI_GPU_IMAGE_SOURCE}" "TEI_GPU_IMAGE_SOURCE"
  gpu_locked="$(resolve_repo_digest "${TEI_GPU_IMAGE_SOURCE}")"

  write_lock_file "${cpu_locked}" "${gpu_locked}"
else
  if [[ ! -f "${LOCK_FILE}" ]]; then
    echo "lock_tei_images.sh: ${LOCK_FILE} not found (run with --update)" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  source "${LOCK_FILE}"
  validate_lock_entry TEI_CPU_IMAGE
  validate_lock_entry TEI_GPU_IMAGE
  echo "lock_tei_images.sh: validation passed"
fi
